export const tmdbConstants = {
  GET_POPULAR_REQUEST: "GET_POPULAR_REQUEST",
  GET_POPULAR_SUCCESS: "GET_POPULAR_SUCCESS",
  GET_POPULAR_FAILURE: "GET_POPULAR_FAILURE",

  GET_TOP_RATED_REQUEST: "GET_TOP_RATED_REQUEST",
  GET_TOP_RATED_SUCCESS: "GET_TOP_RATED_SUCCESS",
  GET_TOP_RATED_FAILURE: "GET_TOP_RATED_FAILURE",

  GET_TRENDING_REQUEST: "GET_TRENDING_REQUEST",
  GET_TRENDING_SUCCESS: "GET_TRENDING_SUCCESS",
  GET_TRENDING_FAILURE: "GET_TRENDING_FAILURE",

  GET_MOVIE_DETAILS_REQUEST: "GET_MOVIE_DETAILS_REQUEST",
  GET_MOVIE_DETAILS_SUCCESS: "GET_MOVIE_DETAILS_SUCCESS",
  GET_MOVIE_DETAILS_FAILURE: "GET_MOVIE_DETAILS_FAILURE",

  GET_MOVIE_CREDITS_REQUEST: "GET_MOVIE_CREDITS_REQUEST",
  GET_MOVIE_CREDITS_SUCCESS: "GET_MOVIE_CREDITS_SUCCESS",
  GET_MOVIE_CREDITS_FAILURE: "GET_MOVIE_CREDITS_FAILURE",

  GET_MOVIE_VIDEOS_REQUEST: "GET_MOVIE_VIDEOS_REQUEST",
  GET_MOVIE_VIDEOS_SUCCESS: "GET_MOVIE_VIDEOS_SUCCESS",
  GET_MOVIE_VIDEOS_FAILURE: "GET_MOVIE_VIDEOS_FAILURE",

  GET_SIMILAR_MOVIES_REQUEST: "GET_SIMILAR_MOVIES_REQUEST",
  GET_SIMILAR_MOVIES_SUCCESS: "GET_SIMILAR_MOVIES_SUCCESS",
  GET_SIMILAR_MOVIES_FAILURE: "GET_SIMILAR_MOVIES_FAILURE",

  SEARCH_MOVIES_REQUEST: "SEARCH_MOVIES_REQUEST",
  SEARCH_MOVIES_SUCCESS: "SEARCH_MOVIES_SUCCESS",
  SEARCH_MOVIES_FAILURE: "SEARCH_MOVIES_FAILURE",
}
