export const tmdbConstants = {
  GET_POPULAR_REQUEST: "GET_POPULAR_REQUEST",
  GET_POPULAR_SUCCESS: "GET_POPULAR_SUCCESS",
  GET_POPULAR_FAILURE: "GET_POPULAR_FAILURE",

  GET_TRENDING_REQUEST: "GET_TRENDING_REQUEST",
  GET_TRENDING_SUCCESS: "GET_TRENDING_SUCCESS",
  GET_TRENDING_FAILURE: "GET_TRENDING_FAILURE",
}
